# Generated by Django 2.0.4 on 2018-04-16 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180415_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255, verbose_name='Role')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('from_month', models.CharField(max_length=255, verbose_name='From Month')),
                ('from_year', models.CharField(max_length=255, verbose_name='From Year')),
                ('to_month', models.CharField(max_length=255, verbose_name='To Month')),
                ('to_year', models.CharField(max_length=255, verbose_name='To Year')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='UserSocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('url', models.CharField(max_length=255, verbose_name='Url')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
