# Generated by Django 2.0.4 on 2018-04-16 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userjob_usersociallink'),
    ]

    operations = [
        migrations.AddField(
            model_name='userjob',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
